name: "Create a GitHub release based on labels in PR"
description: "GitHub Action for creating a release"
author: "mrachuta"
branding:
  icon: 'activity'
  color: 'gray-dark'
inputs:
  token:
    description: "GitHub access token"
    required: true
    type: string
  repository:
    description: "GitHub repostitory name"
    required: true
    type: string
  pull_request_id:
    description: "Pull request to use in release process"
    required: true
    type: number
  mode:
    description: "Mode that action will be using"
    required: false
    type: string

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.repository }}
    - ${{ inputs.pull_request_id }}
    - ${{ inputs.mode }}
