name: "Create a GitHub release based on labels in PR"
description: "GitHub Action for creating a release"
author: "mrachuta"
branding:
  icon: 'activity'
  color: 'gray-dark'
inputs:
  token:
    description: "GitHub access token"
    required: true
    type: string
  repository:
    description: "GitHub repostitory name"
    required: true
    type: string
  pull_request_id:
    description: "Pull request to use in release process"
    required: true
    type: number
  mode:
    description: "Mode that action will be using (validate or release)"
    required: true
    type: string
  custom_tag:
    description: "Custom tag to use in release mode (skips calculation)."
    required: false
    type: string
  debug:
    description: "Enable debug logging"
    required: false
    type: string
  assets:
    description: "Comma-separated list of files or glob patterns to upload as release assets"
    required: false
    type: string
outputs:
  new_tag:
    description: "Tag to be created."
runs:
  using: 'docker'
  image: 'Dockerfile'

