name: Release build
run-name: Release job triggered by ${{ github.event_name }} on ${{ github.ref_name }}

on:
  pull_request:
    branches: [master]
    types: [opened, labeled, unlabeled, closed]

jobs:
  validate-for-release:
    if: |
      github.event.action == 'opened' || github.event.action == 'labeled' || github.event.action == 'unlabeled'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        id: checkout
      - name: Validate for release
        uses: ./
        id: validate_for_release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_id: ${{ github.event.number }}
          mode: comment

  create-release:
    if: |
      github.event.action == 'closed' &&
      github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        id: checkout
      - name: Create release
        uses: ./
        id: create_release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_id: ${{ github.event.number }}
          mode: release
